old/EvaSpa_1.0/EVASPA.Web/Controllers/CardTypeController.cs
using EVASPA.Core.Service;
using EVASPA.Model.DataModel;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace EVASPA.Web.Controllers
{
    public class CardTypeController : ItemController
    {
        protected IItemHistoryService ItemHistoryService { get; set; }

        public CardTypeController(IItemService itemService, IItemHistoryService itemHistoryService)
            : base(itemService)
        {
            ItemHistoryService = itemHistoryService;
        }

        public ActionResult Index()
        {
            var allItems = ItemService.GetAllCardTypes();
            return View(allItems);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var item = ItemService.GetCardTypeById(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.ImportHistories = ItemHistoryService.AllEntities.Where(x => x.ItemId == id).OrderByDescending(x => x.Date);
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DefaultPrice,QuantityInStock,Discontinued")] CardType cardType)
        {
            if (ModelState.IsValid)
            {
                ItemService.Add(cardType);
                return RedirectToAction("Index");
            }
            return View(cardType);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = ItemService.GetCardTypeById(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,DefaultPrice,QuantityInStock,Discontinued")] CardType cardType)
        {
            if (ModelState.IsValid)
            {
                ItemService.Update(cardType);
                return RedirectToAction("Index");
            }
            return View(cardType);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = ItemService.GetCardTypeById(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
    }
}

old/EvaSpa_1.0/EVASPA.Web/Controllers/ItemHistoryController.cs
using EVASPA.Core.Service;
using System.Net;
using System.Web.Mvc;
using EVASPA.Model.DataModel;
using System;
using System.Linq;

namespace EVASPA.Web.Controllers
{
    public class ItemHistoryController : ControllerBase
    {
        IItemService ItemService { get; set; }

        IItemHistoryService ItemHistoryService { get; set; }

        public ItemHistoryController(IItemService itemService, IItemHistoryService itemHistoryService)
        {
            ItemService = itemService;
            ItemHistoryService = itemHistoryService;
        }

        public ActionResult Import(int? itemId)
        {
            if (itemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var item = ItemService.GetById(itemId.Value);
            if (item == null || !(item is Product || item is CardType))
            {
                return HttpNotFound();
            }
            ViewBag.Item = item;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import([Bind(Include="Quantity,Price,Note")] ItemHistory itemhistory,string date, int itemId, string returnUrl)
        {
            var d = DateTime.ParseExact(date, "dd/MM/yyyy", null);
            itemhistory.Date = d;
            itemhistory.ItemId = itemId;

            if (ModelState.IsValid)
            {
                ItemService.Import(itemhistory);
            }

            return RedirectToLocal(returnUrl);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteHistory(int? id)
        {
            var model = ItemHistoryService.AllEntities.FirstOrDefault(x => x.Id == id);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteHistory(int id)
        {
            ItemHistoryService.Delete(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

old/EvaSpa_1.0/EVASPA.Web/Views/CardType/Create.cshtml
@model EVASPA.Model.DataModel.CardType

@{
    ViewBag.Title = "Thêm";
}

<h2>Thêm</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Loại phiếu</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultPrice, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultPrice)
                @Html.ValidationMessageFor(model => model.DefaultPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityInStock, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityInStock)
                @Html.ValidationMessageFor(model => model.QuantityInStock)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discontinued, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discontinued)
                @Html.ValidationMessageFor(model => model.Discontinued)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đồng ý" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<< Quay lại", "Index")
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/CardType/Delete.cshtml
@model EVASPA.Model.DataModel.CardType

@{
    ViewBag.Title = "Xóa";
}

<h2>Xóa</h2>

<h3>Bạn có muốn xóa?</h3>
<div>
    <h4>Loại phiếu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DefaultPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityInStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityInStock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discontinued)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discontinued)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("<< Quay lại", "Index") |
            <input type="submit" value="Đồng ý xóa" class="btn btn-default" />
        </div>
    }
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/CardType/Details.cshtml
@using EVASPA.Model.DataModel
@model CardType

@{
    ViewBag.Title = "Chi tiết";
    var importHistories = ViewBag.ImportHistories as IEnumerable<ItemHistory>;
}

<h2>Chi tiết</h2>

<div>
    <h4>Loại phiếu</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DefaultPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityInStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityInStock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discontinued)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discontinued)
        </dd>

    </dl>
</div>
<div class="panel panel-info">
    <div class="panel-heading text-warning"><strong>Lịch sử nhập hàng</strong></div>
    <table class="table table-striped table-hover table-responsive">
        <thead>
            <tr>
                <th class="col-md-1">Ngày</th>
                <th class="col-md-1">Số lượng</th>
                <th class="col-md-1">Đơn giá</th>
                <th class="col-md-4">Ghi chú</th>
                <th class="col-md-1"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var history in importHistories)
            {
                <tr>
                    <td>@history.Date.ToString("dd/MM/yyyy")</td>
                    <td>@history.Quantity.ToString("#,0")</td>
                    <td>@history.Price.ToString("#,0")</td>
                    <td>@history.Note</td>
                    <td>
                        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                        {
                            @Html.ActionLink("Xóa", "DeleteHistory", "ItemHistory", new { id = history.Id }, null)
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    @Html.ActionLink("<< Quay lại", "Index")
</p>

old/EvaSpa_1.0/EVASPA.Web/Views/CardType/Edit.cshtml
@model EVASPA.Model.DataModel.CardType

@{
    ViewBag.Title = "Sửa";
}

<h2>Sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Loại phiếu</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultPrice, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultPrice)
                @Html.ValidationMessageFor(model => model.DefaultPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityInStock, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityInStock)
                @Html.ValidationMessageFor(model => model.QuantityInStock)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discontinued, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discontinued)
                @Html.ValidationMessageFor(model => model.Discontinued)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<< Quay lại", "Index")
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/CardType/Index.cshtml
@model IEnumerable<EVASPA.Model.DataModel.CardType>

@{
    ViewBag.Title = "Loại phiếu";
}

<h2>Loại phiếu</h2>

<p>
    @Html.ActionLink("Thêm mới...", "Create")
</p>
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantityInStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discontinued)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="number">
                    @Html.DisplayFor(modelItem => item.DefaultPrice)
                </td>
                <td class="number">
                    @Html.DisplayFor(modelItem => item.QuantityInStock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Discontinued)
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Nhập", "Import", "ItemHistory", new { itemId = item.Id, returnUrl = Request.Url.LocalPath }, null) |
                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>