old/EvaSpa_1.0/EVASPA.Web/Controllers/PrepaidCardController.cs
using EVASPA.Core.Service;
using EVASPA.Model.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace EVASPA.Web.Controllers
{
    public class PrepaidCardController : ControllerBase
    {
        private IPrepaidCardService PrepaidCardService { get; set; }
        private IUserService UserService { get; set; }
        private IItemService ItemService { get; set; }

        public PrepaidCardController(IPrepaidCardService prepaidCardService, IUserService userService, IItemService itemService)
        {
            PrepaidCardService = prepaidCardService;
            UserService = userService;
            ItemService = itemService;
        }

        // GET: /PrepaidCard/
        public ActionResult Index()
        {
            var model = new List<PrepaidCard>();

            var allCards = PrepaidCardService.AllCardsWithPreLoadedInfo.OrderBy(x => x.Customer.Name).ToList();
            var PrepaidCardStatuses = new Dictionary<int, string>();
            foreach (var card in allCards)
            {
                if (card.IsLocked)
                    continue;

                var available = PrepaidCardService.GetCardAvailable(card);
                if (available > 0)
                {
                    PrepaidCardStatuses.Add(card.Id, string.Format("{0:#,0.##} / {1:#,0.##}", card.Quota - available, card.Quota));
                    model.Add(card);
                }
            }
            ViewBag.PrepaidCardStatuses = PrepaidCardStatuses;
            return View(model);
        }

        public ActionResult ExpiredCards()
        {
            var model = new List<PrepaidCard>();

            var allCards = PrepaidCardService.AllCardsWithPreLoadedInfo.OrderBy(x => x.Customer.Name).ToList();
            var PrepaidCardStatuses = new Dictionary<int, string>();
            foreach (var card in allCards)
            {
                var available = PrepaidCardService.GetCardAvailable(card);
                if (available <= 0 || card.IsLocked)
                {
                    PrepaidCardStatuses.Add(card.Id, string.Format("{0:#,0} / {1:#,0}", card.Quota - available, card.Quota));
                    model.Add(card);
                }
            }
            ViewBag.PrepaidCardStatuses = PrepaidCardStatuses;
            return View(model);
        }

        // GET: /PrepaidCard/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrepaidCard prepaidcard = PrepaidCardService.GetById(id);
            if (prepaidcard == null)
            {
                return HttpNotFound();
            }
            return View(prepaidcard);
        }

        public ActionResult DetailsBySerial(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrepaidCard prepaidcard = PrepaidCardService.GetBySerialNumber(id);
            if (prepaidcard == null)
            {
                return HttpNotFound();
            }
            return View("Details", prepaidcard);
        }

        // GET: /PrepaidCard/Delete/5
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrepaidCard prepaidcard = PrepaidCardService.GetById(id);
            if (prepaidcard == null)
            {
                return HttpNotFound();
            }
            return View(prepaidcard);
        }

        // POST: /PrepaidCard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            //PrepaidCard prepaidcard = PrepaidCardService.GetById(id);
            //db.PrepaidCards.Remove(prepaidcard);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UseMoneyCard(string id)
        {
            var success = true;
            var msg = string.Empty;
            var available = 0M;
            var cardId = 0;
            if (!string.IsNullOrWhiteSpace(id))
            {
                try
                {
                    id = id.Trim();
                    var card = PrepaidCardService.AllMoneyCards.FirstOrDefault(
                        x => string.Compare(x.SerialNumber, id, StringComparison.OrdinalIgnoreCase) == 0);
                    if (card == null)
                    {
                        throw new Exception("Mã phiếu không đúng");
                    }
                    cardId = card.Id;
                    available = PrepaidCardService.GetCardAvailable(card);
                    if (available <= 0)
                    {
                        throw new Exception("Phiếu đã hết hạn mức sử dụng.");
                    }
                }
                catch (Exception ex)
                {
                    success = false;
                    msg = ex.Message;
                }
            }
            return Json(new { success, msg, available, cardId });
        }

        public ActionResult UseServiceCard(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View("_SelectCard");

            var prepaidcard = PrepaidCardService.GetBySerialNumber(id);
            if (prepaidcard == null)
            {
                ViewBag.Msg = "Phiếu '" + id + "' không tồn tại.";
                return View("_SelectCard");
            }
            if (PrepaidCardService.GetCardAvailable(prepaidcard) <= 0)
            {
                ViewBag.Msg = "Phiếu '" + id + "' đã được sử dụng hết.";
                return View("_SelectCard");
            }
            ViewBag.PrepaidCard = prepaidcard;
            ViewBag.AllEmployees = UserService.AllEmployees;
            ViewBag.AllProducts = ItemService.GetAllProducts();
            return View();
        }

        [HttpPost]
        public ActionResult UseServiceCard(PrepaidServiceCardHistory model, string usedDate, int[] PerformerIds)
        {
            var success = false;
            var msg = "";

            try
            {
                model.Date = DateTime.ParseExact(usedDate, "dd/MM/yyyy", null);
                PrepaidCardService.UseServiceCard(model, PerformerIds);

                success = true;
                msg = Url.Action("Details", new { id = model.PrepaidServiceCardId });
            }
            catch (Exception ex)
            {
                success = false;
                msg = ex.Message;
            }


            return Json(new {success, msg });
        }

        public ActionResult LockCard(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrepaidCard prepaidcard = PrepaidCardService.GetById(id);
            if (prepaidcard == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardSerial = prepaidcard.SerialNumber;
            ViewBag.IsCardLocked = prepaidcard.IsLocked;
            return View();
        }

        [HttpPost, ActionName("LockCard")]
        public ActionResult LockCardConfirmed(string id)
        {
            PrepaidCardService.LockCard(id);
            return RedirectToAction("DetailsBySerial", new { id });
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteHistory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Id = id;
            return View();
        }

        [HttpPost, ActionName("DeleteHistory")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult DeleteHistoryConfirmed(int id)
        {
            var ret = PrepaidCardService.DeleteHistory(id);
            return RedirectToAction("Details", new { id = ret });
        }
    }
}

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/Create.cshtml
@model EVASPA.Model.DataModel.PrepaidCard

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PrepaidCard</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.CardTypeId, "CardTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.CardTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", String.Empty)
                @Html.ValidationMessageFor(model => model.CustomerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber)
                @Html.ValidationMessageFor(model => model.SerialNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldDate)
                @Html.ValidationMessageFor(model => model.SoldDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellMoney, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellMoney)
                @Html.ValidationMessageFor(model => model.SellMoney)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quota, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quota)
                @Html.ValidationMessageFor(model => model.Quota)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/Delete.cshtml
@model EVASPA.Model.DataModel.PrepaidCard

@{
    ViewBag.Title = "Xóa";
}

<h2>Xóa</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PrepaidCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellMoney)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellMoney)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quota)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/DeleteHistory.cshtml
@{
    ViewBag.Title = "Xóa";
}

<h2>Xóa</h2>

<h4>Bạn có muốn xóa việc sử dụng phiếu?</h4>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@ViewBag.Id" />
        <div class="form-actions no-color">
            <input type="submit" value="Đồng ý xóa" class="btn btn-default" />
        </div>
    }
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/Details.cshtml
@using EVASPA.Model.DataModel
@using EVASPA.Web.Utils
@model PrepaidCard

@{
    ViewBag.Title = "Chi tiết phiếu";
}

<h2>Chi tiết phiếu</h2>
@if (Model.IsDeleted)
{
    <div style="text-align:center;">
        <h3 style="color:red;">Phiếu này đã bị xóa!</h3>
    </div>
}
<h4>@(Model is PrepaidMoneyCard ? "Phiếu quà tặng" : "Phiếu dịch vụ")</h4>
<hr />
<div class="panel panel-info">
    <div class="panel-heading text-warning"><strong>Thông tin chung</strong></div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CardType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CardType.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer)
            </dt>

            <dd>
                @Html.EvaSpa_GetCustomerName(Model.Customer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SerialNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SoldDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SoldDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SellMoney)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SellMoney)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quota)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quota)
            </dd>


            @if (Model is PrepaidServiceCard)
            {
                var serviceCard = Model as PrepaidServiceCard;
                <dt>
                    @Html.DisplayNameFor(x => serviceCard.Service)
                </dt>

                <dd>
                    @Html.DisplayFor(x => serviceCard.Service.Name)
                </dd>
            }
            
            <dt>
                @Html.DisplayNameFor(x => Model.IsLocked)
            </dt>

            <dd>
                @if (Model.IsLocked)
                {
                    @Html.DisplayFor(x=>Model.IsLocked) @Html.ActionLink("Mở khóa phiếu", "LockCard", new { Model.Id }, new { style = "padding-left:30px;" })
                }
                else
                {
                    @Html.DisplayFor(x=>Model.IsLocked) @Html.ActionLink("Khóa phiếu", "LockCard", new { Model.Id }, new { style = "padding-left:30px;" })
                }
            </dd>
        </dl>
    </div>
</div>
<div class="panel panel-info">
    <div class="panel-heading text-warning"><strong>Lịch sử</strong></div>
    <table class="table table-striped table-hover table-responsive">
        <thead>
            <tr>
                <th class="col-md-1">Ngày dùng</th>
                @if (Model is PrepaidMoneyCard)
                {
                    <th class="col-md-1">Hóa đơn</th>
                    <th class="col-md-2">Số tiền</th>
                }
                else if (Model is PrepaidServiceCard)
                {
                    <th class="col-md-1">Số suất</th>
                    <th class="col-md-2">Thực hiện</th>
                    <th class="col-md-2">Dùng kèm</th>
                }
                <th class="col-md-4">Ghi chú</th>
                <th class="col-md-1"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model is PrepaidMoneyCard)
            {
                var moneyCard = Model as PrepaidMoneyCard;
                foreach (var history in moneyCard.History.Where(x => !x.IsDeleted).OrderByDescending(x => x.Date))
                {
                    <tr>
                        <td>@Html.DisplayFor(x => history.Date)</td>
                        <td>@Html.ActionLink(history.UsedInBillId.ToString("#,0.##"), "Details", "Bill", new { id = history.UsedInBillId }, null)</td>
                        <td>@Html.DisplayFor(x => history.UsedAmount)</td>
                        <td>@Html.DisplayFor(x => history.Note)</td>
                    </tr>
                }
            }
            else if (Model is PrepaidServiceCard)
            {
                var serviceCard = Model as PrepaidServiceCard;
                foreach (var history in serviceCard.History.Where(x => !x.IsDeleted).OrderByDescending(x => x.Date))
                {
                    <tr>
                        <td>@Html.DisplayFor(x => history.Date)</td>
                        <td>@history.UsedAmount.ToString("#,0.##")</td>
                        <td>@string.Join(", ", history.Performers.Select(i => i.DisplayName))</td>
                        <td>@string.Join(", ", history.UsedProducts.Select(i => i.Product.Name +" ("+i.Quantity.ToString()+")"))</td>
                        <td>@Html.DisplayFor(x => history.Note)</td>
                        @if (User.IsInRoles("Admin", "Manager"))
                        {
                            <td>@Html.ActionLink("Xóa", "DeleteHistory", new { id = history.Id })</td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<p>
    @Html.ActionLink("<< Quay lại", "Index")
</p>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/Edit.cshtml
@model EVASPA.Model.DataModel.PrepaidCard

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PrepaidCard</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CardTypeId, "CardTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.CardTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", String.Empty)
                @Html.ValidationMessageFor(model => model.CustomerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber)
                @Html.ValidationMessageFor(model => model.SerialNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldDate)
                @Html.ValidationMessageFor(model => model.SoldDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellMoney, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellMoney)
                @Html.ValidationMessageFor(model => model.SellMoney)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quota, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quota)
                @Html.ValidationMessageFor(model => model.Quota)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/ExpiredCards.cshtml
@using EVASPA.Model.DataModel
@using EVASPA.Web.Utils
@model IEnumerable<PrepaidCard>

@{
    ViewBag.Title = "Phiếu hết hạn";

    var PrepaidCardStatuses = ViewBag.PrepaidCardStatuses as Dictionary<int, string> ?? new Dictionary<int, string>();
}

<h2>Phiếu hết hạn</h2>

<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                Khách hàng
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CardType)
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                Sử dụng
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoldDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNumber)
                </td>
                <td>
                    @Html.EvaSpa_GetCustomerName(item.Customer)
                </td>
                @if (item is PrepaidMoneyCard)
                {
                    <td>
                        <div>Phiếu quà tặng - <strong>@item.CardType.Name</strong></div>
                        <div class="sub">Hạn mức: <em>@Html.DisplayFor(x => item.Quota)</em></div>
                    </td>
                }
                else if (item is PrepaidServiceCard)
                {
                    <td>
                        <div>Phiếu dịch vụ - <strong>@item.CardType.Name</strong></div>
                        <div class="sub">Dịch vụ: <em>@((item as PrepaidServiceCard).Service.Name)</em></div>
                        <div class="sub">Hạn mức: <em>@Html.DisplayFor(x => item.Quota)</em></div>
                    </td>
                }
                <td>@(item.IsLocked ? "Đã khóa" :string.Empty)</td>
                <td>@PrepaidCardStatuses[item.Id]</td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoldDate)
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })

                    @if (item is PrepaidServiceCard)
                    {
                        @:| @Html.ActionLink("Sử dụng", "UseServiceCard", new { id = item.SerialNumber })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/Index.cshtml
@using EVASPA.Model.DataModel
@using EVASPA.Web.Utils
@model IEnumerable<PrepaidCard>

@{
    ViewBag.Title = "Phiếu";

    var PrepaidCardStatuses = ViewBag.PrepaidCardStatuses as Dictionary<int, string> ?? new Dictionary<int, string>();
}

<h2>Phiếu</h2>
<div style="text-align:right;">
    @Html.ActionLink("Xem phiếu hết hạn >>", "ExpiredCards", null, new { target="_blank" })
</div>
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                Khách hàng
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CardType)
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoldDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNumber)
                </td>
                <td>
                    @Html.EvaSpa_GetCustomerName(item.Customer)
                </td>
                @if (item is PrepaidMoneyCard)
                {
                    <td>
                        <div>Phiếu quà tặng - <strong>@item.CardType.Name</strong></div>
                        <div class="sub">Hạn mức: <em>@Html.DisplayFor(x => item.Quota)</em></div>
                    </td>
                }
                else if (item is PrepaidServiceCard)
                {
                    <td>
                        <div>Phiếu dịch vụ - <strong>@item.CardType.Name</strong></div>
                        <div class="sub">Dịch vụ: <em>@((item as PrepaidServiceCard).Service.Name)</em></div>
                        <div class="sub">Hạn mức: <em>@Html.DisplayFor(x => item.Quota)</em></div>
                    </td>
                }
                <td>@PrepaidCardStatuses[item.Id]</td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoldDate)
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })
                    
                    @if (item is PrepaidServiceCard)
                    {
                        @:| @Html.ActionLink("Sử dụng", "UseServiceCard", new { id = item.SerialNumber })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/LockCard.cshtml
@{
    var isCardLocked = (bool)ViewBag.IsCardLocked;
    var title = isCardLocked ? "Mở khóa phiếu" : "Khóa phiếu";
    ViewBag.Title = title;
}

<h2>@title</h2>

<h4>Bạn có muốn @title.ToLower() <b>@ViewBag.CardSerial</b>?</h4>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@ViewBag.CardSerial" />
        <div class="form-actions no-color">
            <input type="submit" value="Đồng ý" class="btn btn-default" />
        </div>
    }
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/_PrepaidServiceCardBasicInfo.cshtml
@using EVASPA.Web.Utils
@model EVASPA.Model.DataModel.PrepaidServiceCard
<div class="panel panel-info">
    <div class="panel-heading text-warning"><strong>Thông tin phiếu</strong></div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CardType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CardType.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer)
            </dt>

            <dd>
                @Html.EvaSpa_GetCustomerName(Model.Customer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SerialNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SoldDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SoldDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SellMoney)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SellMoney)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quota)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quota)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Service)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Service.Name)
            </dd>
        </dl>
    </div>
</div>

old/EvaSpa_1.0/EVASPA.Web/Views/PrepaidCard/_SelectCard.cshtml
@{
    ViewBag.Title = "Dùng phiếu dịch vụ";

    var msg = ViewBag.Msg as string ?? "";
}

<h2>Dùng phiếu dịch vụ</h2>

@using (Html.BeginForm("UseServiceCard", "PrepaidCard", FormMethod.Get))
{
    <hr />

    <div class="row">
        <div class="col-md-2"><label>Mã phiếu</label></div>
        <div class="col-md-3">
            <input name="id" type="text" />
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-3 important red">
            @msg
        </div>
    </div>

    <div class="row">
        <div class="col-md-2"></div>
        <input type="submit" value="Đồng ý" class="btn btn-primary" />
    </div>
}